# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_m', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AP',
            fields=[
                ('AP_id', models.IntegerField(primary_key=True, serialize=False)),
                ('week1_p', models.CharField(max_length=3, null=True)),
                ('week1_A', models.CharField(max_length=3, null=True)),
                ('week2_p', models.CharField(max_length=3, null=True)),
                ('week2_A', models.CharField(max_length=3, null=True)),
                ('week3_p', models.CharField(max_length=3, null=True)),
                ('week3_A', models.CharField(max_length=3, null=True)),
                ('week4_p', models.CharField(max_length=3, null=True)),
                ('week4_A', models.CharField(max_length=3, null=True)),
                ('week5_p', models.CharField(max_length=3, null=True)),
                ('week5_A', models.CharField(max_length=3, null=True)),
                ('week6_p', models.CharField(max_length=3, null=True)),
                ('week6_A', models.CharField(max_length=3, null=True)),
                ('week7_p', models.CharField(max_length=3, null=True)),
                ('week7_A', models.CharField(max_length=3, null=True)),
                ('week8_p', models.CharField(max_length=3, null=True)),
                ('week8_A', models.CharField(max_length=3, null=True)),
                ('week9_p', models.CharField(max_length=3, null=True)),
                ('week9_A', models.CharField(max_length=3, null=True)),
                ('week10_p', models.CharField(max_length=3, null=True)),
                ('week10_A', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=300)),
                ('comments', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=32)),
                ('student_AP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.AP')),
                ('student_FC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.FC')),
            ],
        ),
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='ap',
            name='sutdend_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Students'),
        ),
    ]
