# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-20 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190520_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ap',
            name='sutdend_ID',
        ),
    ]
